# hello-world.sub
# My HTCondor submit file

container_image = file:///staging/jjanderson27/matlab-2023b.sif

executable = run_sim.sh
arguments = $(prop_formation_rate) $(separation_distance) $(sites)
   		
log = output/sim.log
error = output/sim.err
output = output//sim.out
   
transfer_input_files = Functions/

requirements = (Target.HasCHTCStaging == True)

request_cpus = 2
request_memory = 64GB
request_disk = 4GB
concurrency_limits = MATLAB:1
max_idle = 2000
   
queue prop_formation_rate,separation_distance,sites from params.txt
